### PR TITLE
fix #6

### LINKED ISSUE #6: installlation error
if i'm installing the app as instruckted by the readme file. https://github.com/wwaites/saved_fisdat/blob/caef6656bab07aeb539359417d9fdb934b3cb0e8/README.md?plain=1#L9-L19

my commands:
```bash
git clone git@github.com:wwaites/saved_fisdat.git
cd saved_fisdat/
git submodule init && git submodule update
python -m venv .venv
source .venv/bin/activate
python setup.py install
```
I get
```
error: The 'linkml' distribution was not found and is required by   fisdat
```
reset
```bash
cd ..
rm -rf saved_fisdat
```

But using `pip` to install the package:
```bash
git clone git@github.com:wwaites/saved_fisdat.git
cd saved_fisdat/
git submodule init && git submodule update
python -m venv .venv
source .venv/bin/activate
python -m pip install .
```
it installs

```bash
cd ..
ls $(python -c 'import pathlib, fisdat; print(pathlib.Path(fisdat.__file__).parent)')/..|grep data-model
```
but `fisdat/../data-model` is not to be found as requierd by: https://github.com/wwaites/saved_fisdat/blob/caef6656bab07aeb539359417d9fdb934b3cb0e8/fisdat/cmd_dat.py#L231

### PR DESCRIPTION
**Pull request by TrondurT**
fix #6 

I have changed README.md file to use pip to install the package.

I have moved the submodule, so that is comes along in the install updated the refrenses to the submodule in the relevent places.

### CODE REVIEW

**Comment by druimalban** [comment]
Thanks, you're right about the README instructions - I couldn't get that to work either.

I have taken your modifications (move data-model -> fisdat/data-model &c) and used importlib to import the file. This seems to work regardless of current working directory.

The examples still use absolute paths, I will update these…

Could you see if this modification works for you?

**Comment by druimalban** [comment]
For the examples, when we are able to host the data model somewhere externally, we can avoid using an absolute path to the data model.

**Comment by druimalban** [comment]
You could try removing the `fisdat/data_model` directory and then `git checkout -- fisdat/data_model`? 

Perhaps also there is an interaction with the virtual environment, I had to remove mine and follow the steps in the readme file to reproduce your problem.

**Comment by TrondurT** [comment]
where are you running the script from???

**Comment by druimalban** [comment]
The workflow I have is to source the virtualenv, then I run `python setup.py develop` and it usually picks up changes immediately.

I had a similar result with `python setup.py install` albeit it was annoying when making many changes as I kept having to run it.

I tested running fisdat, fisup in `/tmp` and in the `examples/sentinel_cages` directory of the repository check-out.

When working with your changes, I worked in a fresh checkout of the repository and used the `gh` CLI tool to fetch yours.

The interaction of the virtual environment with `setup.py` interaction is quite opaque to me.

**Comment by TrondurT** [comment]
I see

[stackoverflow](https://stackoverflow.com/questions/19048732/python-setup-py-develop-vs-install)

so you are using the files that are in the git reposotory and not installing the package into site-packages.
And therefore the yaml files are relative to the script files.

**Comment by wwaites** [comment]
The secret to not being annoyed is to run `python setup.py develop`. This installs the module to python's `site-packages` as symlinks with some metadata to your checked out tree. Using `install` copies the module which is why you have to keep re-running it.

**Comment by wwaites** [comment]
Similar can be accomplished with `python -m pip install -e .`

**Pull request merged**
